app/urls.py
from django.conf.urls import url
from .views import index, download

urlpatterns = [
    url(r'^$', index.as_view(), name='index'),
    url(r'download/$', download, name='download'),
]

lineas_base_seguridad/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('app.urls', namespace='app')),
    url(r'^admin/', admin.site.urls),
]

app/models.py
# -*- coding: utf-8 -*-
from django.db import models


class SistemaOperativo(models.Model):
    nombre = models.CharField(max_length=40)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return '{}'.format(self.nombre)
    
    class Meta:
        verbose_name = 'Sistema Operativo'
        verbose_name_plural = '1. Parametrización de Sistemas Operativos'

    
class Capitulo(models.Model):
    nombre = models.CharField(max_length=250)
    descripcion = models.TextField(blank=True)
    sistema_operativo = models.ManyToManyField(SistemaOperativo)
    
    def sistemas_operativos(self):
        return ', '.join([str(os) for os in self.sistema_operativo.all()])
    
    def __str__(self):
        return '{}'.format(self.nombre)
    
    class Meta:
        verbose_name = 'Categoría de configuración'
        verbose_name_plural = '2. Parametrización de categorías de configuración'


class SubCapitulo(models.Model):
    nombre = models.CharField(max_length=250)
    capitulo = models.ForeignKey(Capitulo, null=False, blank=False) 
    sistema_operativo = models.ManyToManyField(SistemaOperativo, blank=True)
    comandos = models.TextField(blank=False)
    descripcion = models.TextField(blank=True)
    
    def sistemas_operativos(self):
        return ', '.join([str(os) for os in self.sistema_operativo.all()])
    
    def categorias_de_configuracion(self):
        return self.capitulo
    
    def __str__(self):
        return '{}'.format(self.nombre)
    
    class Meta:
        verbose_name = 'Comandos para auditar configuración'
        verbose_name_plural = '3. Parametrización de comandos para auditar configuraciones'
    

app/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Capitulo, SubCapitulo
from django.contrib import admin


class CapituloForm(forms.ModelForm):    
    
    class Meta:
        model = Capitulo
        
        fields = ['nombre', 'descripcion', 'sistema_operativo']
        
        widgets = {
            'sistema_operativo': forms.CheckboxSelectMultiple(),
        } 


class CapituloFormAdmin(admin.ModelAdmin):    
    
    list_display = ('nombre', 'descripcion', 'sistemas_operativos')
    search_fields = ['nombre', 'descripcion', ]
    
    form = CapituloForm


class SubCapituloForm(forms.ModelForm):

    class Meta:
        model = SubCapitulo
        
        fields = ['nombre', 'capitulo', 'sistema_operativo', 'comandos', 'descripcion']  
        
        labels = {
            'capitulo' : 'Categoría de configuración',
        }
        
        widgets = {
            'sistema_operativo': forms.CheckboxSelectMultiple(),
        }   


class SubCapituloFormAdmin(admin.ModelAdmin):
    list_display = ('nombre', 'categorias_de_configuracion', 'sistemas_operativos')
    search_fields = ['nombre', 'capitulo', ]
    
    form = SubCapituloForm

app/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.views.generic import ListView
from app.models import *


class index(ListView):
    model = SistemaOperativo
    template_name = 'form.html'


def download(request):
    sistema_operativo = SistemaOperativo.objects.get(pk=request.POST.get('so'))
    capitulos = sistema_operativo.capitulo_set.all()
    data = []
    
    for capitulo in capitulos:
        subcapitulos = []
        for subcapitulo in sistema_operativo.subcapitulo_set.filter(capitulo = capitulo):
            subcapitulos.append(subcapitulo)
        
        data.append({'capitulo' : capitulo.nombre, 'subcapitulos' : subcapitulos})  
        
    response = render_to_response('download.html', {'sistema_operativo': sistema_operativo, 'data': data})
    response['Content-Type'] = 'text/plain; charset=utf-8'
    response['Content-Disposition'] = 'attachment; filename=%s_script.sh' % sistema_operativo.nombre.replace(" ", "_")
    
    return response

templates/download.html
#! /bin/bash

#################################################################################
#
#   Script Lineas Base de Seguridad v1.0
#   Sistema Operativo: {{ sistema_operativo }}
#   Generado el {% now "j F Y - H:i" %}
#
#################################################################################

{
echo "Iniciando..."
echo "Hostname: $(hostname)"
echo "Fecha: $(date +%Y-%m-%d)"
echo ""
echo ""
echo "---------------------------------------------------------------------------"
{% for linea in data %}
echo ">> Categoría de configuración: {{ linea.capitulo }}"
{% for subcapitulo in linea.subcapitulos %}
echo "* Configuración auditada: {{ subcapitulo.nombre }}"
{{ subcapitulo.comandos|safe }}
{% endfor %}
{% endfor %}
} > "{{ sistema_operativo }}_script_out_$(date +%Y-%m-%d).txt"

templates/form.html
{% extends 'index.html' %}

{% block content %}
<h3>Bienvenido,</h3>
<p align="justify">Le informamos que con este formulario es posible descargar el script para verficar las L&iacute;neas de Seguridad en distribuciones de Linux.</p>
<p align="justify">Por favor, seleccione la distribución de acuerdo a su necesidad y a continuaci&oacute;n, accione el bot&oacute;n "Descargar".</p>
<form method="POST" action="{% url 'app:download' %}">
	{% csrf_token %}
	<div class="row">
		<div class="col-md-3">
			<label for="so">Distribución Linux:</label>	
			<select class="form-control" id="so" name="so">
			{% if object_list %}
				{% for so in object_list %}
					<option value='{{ so.id }}'>{{ so.nombre }}</option>
				{% endfor %}
			{% endif %}
			</select><br />
			<button class="btn btn-primary"><span class="glyphicon glyphicon-download-alt"></span> Descargar</button>
		</div>
		<div class="col-md-2">
		</div>
	</div>
	
	
</form>
{% endblock %}

templates/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>L&iacute;neas Base de Seguridad</title>
		
		<script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/bootstrap-3.3.7/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/bootstrap-3.3.7/css/bootstrap-theme.min.css' %}">
		<script type="text/javascript" src="{% static 'css/bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/errorlist.css' %}">
	</head>
	<body>
		{% block nav %}
	<nav class="navbar navbar-default">
	  	<div class="container-fluid">
	    	<div class="navbar-header">
	      		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
	        	<span class="icon-bar"></span>
	        	<span class="icon-bar"></span>
	        	<span class="icon-bar"></span>                        
	      	</button>
	      	<a class="navbar-brand" href="{% url 'app:index' %}">L&iacute;neas Base de Seguridad</a>
	    </div>
	    <div class="collapse navbar-collapse" id="myNavbar">
	      	<ul class="nav navbar-nav">
	        	{% if user.is_authenticated %}
		        	{% if user.is_active and user.is_staff %}
					<li><a href="{% url 'admin:index' %}">VER LA ADMINISTRACI&Oacute;N</a></li>
	                {% endif %}
	        	{% endif %}
	      	</ul>
	      	<ul class="nav navbar-nav navbar-right">
	      		{% if user.is_authenticated %}
				<li>
	          		<a class="dropdown-toggle" data-toggle="dropdown" href="#">Hola, {% firstof user.get_short_name user.get_username %}</a>
	        	</li>
	        	{% endif %}
	      	</ul>
    	</div>
	  </div>
	</nav>
	{% endblock %}
		
		<div class="container">
		{% block content %}
		Bloque de contenido
		{% endblock %}
		</div>
	</body>
</html>